Exception in thread Thread-1 (receive):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adry/final/csc376_final/client2/../ChatClient.py", line 95, in receive
    port_recv = decode_recv(sock)
                ^^^^^^^^^^^^^^^^^
  File "/home/adry/final/csc376_final/client2/../ChatClient.py", line 88, in decode_recv
    grab_port = int(split_bytes[0])
                ^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
